inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.github/**/*'
    - 'lib/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/OrderedArguments:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false