# Exported from Render on 2024-08-13T19:45:45Z
databases:
- name: postgres
  databaseName: cafe_react_production
  user: cafe_react_production_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "15"
services:
- type: web
  name: cafe_react
  runtime: ruby
  repo: https://github.com/monsieurkayode/cafe_react
  plan: free
  envVars:
  - key: POSTGRES_DB
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: postgres
      property: connectionString
  region: ohio
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bin/webpack;
  startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
version: "1"
