name: Bundler audit 💎
on: [ pull_request ]

env:
  RUBY_VERSION: 2.6.7

jobs:
  bundler_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Security audit dependencies
        uses: tomferreira/action-bundler-audit@v1
        with:
          bundler_audit_version: gemfile
          reporter: github-pr-review
