name: Bundler audit 💎
on: [ pull_request ]

env:
  RUBY_VERSION: 2.6.7

jobs:
  brakeman:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs bundler-audit
      - name: Security audit dependencies
        run: bin/bundler-audit --update
